### ISSUE TITLE
Quality of the image created from PDF

### ISSUE THREAD

**Issue by MichalJirkatesena** [Tesena-smart-testing/WatchUI#55]
Hi, 
I was using WatchUI library in my project for converting PDF into the image format (by PDF To Image keyword). 
After a small research I found out that the image created by this library is slightly different than the image created by pdf2image library (using the same PDF file). 

This image has a lower quality in term of resolution (hight x width) and of course the size of the file. 

Could you please check it out?

**Comment by janegermaier** [comment]
Hi,
Sorry for my later answer but i was busy during Christmas.

Now to your problem, I check it and we going to release 2nd week in year with repair some trouble and i add new atribute for keyword PDF to Image, where you can set the image resolution.

**Comment by janegermaier** [comment]
Hi, 
I have time so i release new version today. We create for pdf to image keyword new arguments "zoom".

More you can find in our [Documentation](https://tesena-smart-testing.github.io/WatchUI/keywords.html#pdf-to-image)
