### ISSUE TITLE
README.md propagation to Pip is incorrect - problems with chars and images

### ISSUE THREAD

**Issue by marcel-veselka** [Tesena-smart-testing/WatchUI#59]
Readme file propagated from GitHub doesn't show properly some characters + images are not propagated as well.

https://pypi.org/project/WatchUI/

See issues with characters:
<img width="397" alt="chars" src="https://user-images.githubusercontent.com/9706465/103348381-1dc80980-4a9a-11eb-857b-f87142f49275.png">

See issues with images:
<img width="287" alt="imgs" src="https://user-images.githubusercontent.com/9706465/103348430-4223e600-4a9a-11eb-8475-382435f37f28.png">

**Comment by janegermaier** [comment]
Chars was repaired in new release (v1.0.10). I going to repairing image in next release (v1.0.11). Thanks for report :-)

**Comment by janegermaier** [comment]
Hi,
today i repaired bug :-) 

More u´ll see [here.](https://pypi.org/project/WatchUI/)
