### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by marcel-veselka** [Tesena-smart-testing/WatchUI#60]
According documentation alternative way to install WatchUI is pull repo, install dependencies via pip and import WatchUI.py file.

This is not possible due to missing requirements.txt file in main repository.

Please add the file to main repo.

**Comment by janegermaier** [comment]
Hi,
We goingto to repair in next reales. We want to release it the second week in Jan.

**Comment by janegermaier** [comment]
Requirements.txt add. So I close issue.
