### ISSUE TITLE
No library 'SeleniumLibrary' found.

### ISSUE THREAD

**Issue by adasup** [Tesena-smart-testing/WatchUI#72]
Hi,

when running simple test

*** Settings ***
Library         WatchUI

*** Variables ***
${DEBUG}  ${True} 

*** Test Cases ***
Test1
    pdf to image  pdfko.pdf  name=obr1.png

it's throwing this error:
Error in file 'C:\Users\ext98311\Documents\doctestlib\dtl.robot' on line 2: Initializing library 'WatchUI' with no arguments failed: No library 'SeleniumLibrary' found.
Traceback (most recent call last):
  File "C:\Users\ext98311\AppData\Roaming\Python\Python37\site-packages\WatchUI\WatchUI.py", line 77, in __init__
    self.seleniumlib = BuiltIn().get_library_instance("SeleniumLibrary")
  File "C:\Users\ext98311\AppData\Roaming\Python\Python37\site-packages\robot\libraries\BuiltIn.py", line 3557, in get_library_instance
    raise RuntimeError(unic(err))

even though, I have everything installed. 
My pip list here:
Appium-Python-Client              1.2.0
astroid                           2.6.6
attrs                             21.2.0
backports.cached-property         1.0.1
backports.entry-points-selectable 1.1.0
bcrypt                            3.2.0
cached-property                   1.5.2
certifi                           2021.5.30
cffi                              1.14.6
charset-normalizer                2.0.4
colorama                          0.4.4
coverage                          5.5
cryptography                      3.4.7
cycler                            0.10.0
decorator                         5.0.9
distlib                           0.3.2
docutils                          0.17.1
et-xmlfile                        1.1.0
Faker                             8.11.0
filelock                          3.0.12
greenlet                          1.1.1
grpcio                            1.38.1
grpcio-tools                      1.38.1
idna                              3.2
imageio                           2.9.0
importlib-metadata                4.6.4
imutils                           0.5.4
isodate                           0.6.0
isort                             5.9.3
joblib                            1.0.1
jsonpath-rw                       1.4.0
jsonpath-rw-ext                   1.2.2
kafka-python                      2.0.2
kitchen                           1.2.6
kiwisolver                        1.3.1
lazy-object-proxy                 1.6.0
lxml                              4.6.3
Mako                              1.1.5
Markdown                          3.3.4
MarkupSafe                        2.0.1
matplotlib                        3.4.3
mccabe                            0.6.1
networkx                          2.6.2
numpy                             1.21.2
opencv-python                     4.5.3.56
openpyxl                          3.0.7
overrides                         6.1.0
pandas                            1.3.2
paramiko                          2.7.2
pbr                               5.6.0
pdfminer                          20191125
pdoc3                             0.10.0
Pillow                            8.3.1
pip                               21.2.2
platformdirs                      2.2.0
pluggy                            0.13.1
ply                               3.11
protobuf                          3.17.3
psycopg2                          2.9.1
py                                1.10.0
pycparser                         2.20
pycryptodome                      3.10.1
pylint                            2.9.6
PyMuPDF                           1.18.16
PyNaCl                            1.4.0
pyparsing                         2.4.7
pytesseract                       0.3.8
python-dateutil                   2.8.2
pytz                              2021.1
PyWavelets                        1.1.1
requests                          2.26.0
requests-file                     1.5.1
requests-toolbelt                 0.9.1
robotframework                    4.1
robotframework-appiumlibrary      1.6.2
robotframework-archivelibrary     0.4.1
robotframework-assertion-engine   0.2.0
robotframework-browser            6.0.0
robotframework-csvlib             1.0.2
robotframework-databaselib        0.2.1
robotframework-databaselibrary    1.2.4
robotframework-excellentlibrary   1.0.0
robotframework-excellib           2.0.1
robotframework-faker              5.0.0
robotframework-jsonlibrary        0.3.1
robotframework-kafkalibrary       0.0.3
robotframework-lint               1.1
robotframework-pabot              2.0.1
robotframework-postgresqldb       2.0.0
robotframework-pythonlibcore      3.0.0
robotframework-requests           0.9.1
robotframework-seleniumlibrary    5.1.3
robotframework-soaplibrary        0.6
robotframework-sshlibrary         3.7.0
robotframework-stacktrace         0.4.1
robotframework-sudslibrary3       1.0
scikit-image                      0.18.2
scikit-learn                      0.24.2
scipy                             1.7.1
scp                               0.13.6
selenium                          3.141.0
semantic-version                  2.8.5
setuptools                        57.4.0
setuptools-git                    1.2
setuptools-rust                   0.11.6
setuptools-scm                    6.0.1
six                               1.16.0
SQLAlchemy                        1.4.23
sqlparse                          0.4.1
suds-jurko                        0.6
suds-py3                          1.4.4.1
text-unidecode                    1.3
threadpoolctl                     2.2.0
tifffile                          2021.8.8
toml                              0.10.2
tox                               3.0.0
typed-ast                         1.4.3
typing-extensions                 3.10.0.0
typing-utils                      0.1.0
urllib3                           1.26.6
virtualenv                        20.7.2
WatchUI                           1.0.11
wheel                             0.36.2
wrapt                             1.12.1
zeep                              4.1.0
zipp                              3.5.0

**Comment by procesor2017** [comment]
Hi,
this is weird bug. But I hope that this helps:
*** Settings ***
Library                         SeleniumLibrary
Library                         WatchUI

In new version WatchUI we want have separately selenium and WatchUI so this mistake will be a thing of the past.

**Comment by adasup** [comment]
Sadly, it didn't help. :( Ok, I'm looking forward new verison. 
Thx

**Comment by procesor2017** [comment]
I tried it with myself, I'm totally sure I know why the error occurs. 
Because the library is initialized with the fact, that seleniumLibrary must be found, it must always be over on the WatchUI.

So this is works:
*** Settings ***
Library       SeleniumLibrary
Library       WatchUI

So this NEVER works:
*** Settings ***
Library       WatchUI
Library       SeleniumLibrary

Please can u try it?

**Comment by radekBednarik** [comment]
@adasup hi, WatchUI imports instance of the SeleniumLibrary to be able to use its method to capture screenshots. If there is no instance, it will fail. That is why you have to import SeleniumLibrary first, as @procesor2017 describes above.

**Comment by adasup** [comment]
You're right, I just added SeleniumLib under. It works, thank you.
