### ISSUE TITLE
Messages of deprecation occurred while the version of "PyMuPDF" was newer than 1.19.0

### ISSUE THREAD

**Issue by chenny2169** [Tesena-smart-testing/WatchUI#77]
Hi,
I was using `WatchUI` for converting PDF documentations into image format by the keyword: `Pdf To Image`. Three warning messages were found right after executing the robot test. The following is the test script that reproduces this issue:

```Robot Framework
*** Settings ***
Library    WatchUI

*** Variables ***
${PDFFilePath} =    path${/}to${/}pdf

*** Test Cases ***
Test Convert PDF to PNG Format
    Pdf To Image    ${PDFFilePath}    ${CURDIR}
```

The versions of the packages are:
* Python: `3.7.4`
* WatchUI: `1.0.11`
* PyMuPDF: `1.19.3` (Installed when `pip install` WatchUI)

After executing the test script above, three messages mentioning that the functions are deprecated are found:

```
Deprecation: 'loadPage' removed from class 'Document' after v1.19 - use 'load_page'.
Deprecation: 'getPixmap' removed from class 'Page' after v1.19 - use 'get_pixmap'.
Deprecation: 'writePNG' removed from class 'Pixmap' after v1.19 - use 'save'.
```

After a brief research on these messages, I found these might be related to the version of `PyMuPDF`. According to the [Deprecated Names List of version 1.19.3](https://pymupdf.readthedocs.io/en/latest/znames.html), all three functions mentioned in the messages are noted. These messages are **not** found after downgrading `PyMuPDF` to `1.18.19`.

I was wondering if you could look into this issue? Thank you.

**Comment by marcel-veselka** [comment]
Hi @chenny2169,

thanks for the report. Actually, we are currently working on WatchUI 2.0 (to be released in Q1-2022).
This also addresses this issue however version 2.0 will also introduce breaking changes.

We will fix this also in version 1 of WatchUI to support also users who are not willing to move to our new version.

Thanks for the great report and the proposed workaround for other WatchUI users.
