### ISSUE TITLE
Issues in robot framework

### ISSUE THREAD

**Issue by tuyenlq** [Tesena-smart-testing/WatchUI#8]
Hi, I have problem with WatchUI on robotframework 

https://imgur.com/a/3LyiKv7

evn : python 3.7.6
pip list in attach file 
[listpip.txt](https://github.com/Tesena-smart-testing/WatchUI/files/4353674/listpip.txt)

You can help me solve problems?
Thanks

**Comment by janegermaier** [comment]
Hi,
From your image, I think that you have problem with importing the library into RF.

Did you follow these installation instructions?

1. Open CMD
2. Start pip install WatchUI
3. Now you can download WatchUI.py from repository or import WatchUI to new python file more [here](https://stackoverflow.com/questions/32952106/creating-a-robot-framework-library-from-existing-python-package)
4. If you download WatchUI.py: You must first enter the path in Settings => Library path, where path is the path to the WatchUI.py file

P.s. Currently, we have only here beta version and we have this complicated install on our TODO list. As soon as there is an improvement I will definitely write here that there is a new version to download that already has this complicated installation solved.

**Comment by tuyenlq** [comment]
Hi,
I tried but it not working in new version WatchUI==0.16.4, i download and added file WatchUI.py on Library on robot framework.
Thanks

**Comment by janegermaier** [comment]
Hi,
We have some troubles with package (It doesnt install all dependencies). Now, if you update your package (ver 0.16.6) you will be alright :-)
For update use cmd: `pip install --upgrade WatchUI` 

For second question: We using windows and linux with Pycharm, but we using Manual install so we have some trouble with package :-)
Sorry for complicating and thank you for your feedback.

Ps: If you have some trouble please send me your system (win or linux) and IDLE which you using.

**Comment by tuyenlq** [comment]
Hi, 
I tried following your instructions but it didn't work.
I run test on windows  
      `Windows 10 pro 64 bit`
      `Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32`

I have tried on on pycharm, didn't work. => https://imgur.com/a/QpuKXiR
and on robotframework-ride , didn't work => https://imgur.com/a/2LgmaAJ

List pip attach
[list.txt](https://github.com/Tesena-smart-testing/WatchUI/files/4360191/list.txt)

Thanks

**Comment by janegermaier** [comment]
Hi,
Im not sure about rabotframework-ride but in Pyharm we can try easy solutions.
1) Copy WatchUI.py and paste to Robot Framework folder
2) in *** SETTINGS *** change line 5 `Library ../WatchUI/WatchUI.py` on `Library WatchUI.py`
3) Try to start some test

What happen? Please send me the screen again :-)

Thanks for your answer :-)

**Comment by tuyenlq** [comment]
Hi,
I tried with your new example , it work on robotframework-ride and pycharm :D

Thank for support me

**Comment by janegermaier** [comment]
Hi,
No problem nad I hope you enjoy ours library :-)
