### ISSUE TITLE
Add option to choose extended selenium library

### ISSUE THREAD

**Issue by eldaduzman** [Tesena-smart-testing/WatchUI#81]
Hi Team Tesena,

WatchUI is an awesome tool and I was more than happy to write about it on better programming (https://betterprogramming.pub/visual-web-testing-with-robot-framework-selenium-and-watchui-417408a6784d)

One thing that is missing though is the ability to work with costumed SeleniumLib extensions (for example, the one you guys developed for Healenium).

In 'WatchUi.py' at line 99, the library name is hard coded 
`self.seleniumlib = BuiltIn().get_library_instance("SeleniumLibrary")`

Such that if I wanted to use Healenium instead that will not work.

I was able to work around it by making 3 changes:

1. add an extra input at the __init__.py of watch ui class(line 64): `def __init__(self, outputs_folder=save_folder_path, ssim_basic=starts_ssim, format_image=starts_format_image, tesseract_path=path_to_tesseract_folder, libname='SeleniumLibrary')`
2. Instead of hard coded 'SeleniumLibrary' I changed line 99 to `self.seleniumlib = BuiltIn().get_library_instance(libname)`
3. in the test script I imported Watch UI with :
`
Library   modules\\HealeniumLibrary.py
Library           WatchUI      libname=HealeniumLibrary

`
This can add flexibility to the lib.

**Comment by janegermaier** [comment]
Hi,
We know about the bad decision, which we made it in this version of the library, and with the new version of the WatchUI, We want to be completely independent of seleniumlibrary, so the library can be used with playwright or others tools. 
The library will only use image comparison, tesseract, etc., but will not depend on selenium in any way :-)

The new version should be here by the end of March. If u want, u can create pull request for your ideas and I will approve it as soon as possible and publish it on pip or u can wait for new version WatchUI-v2

Thank u for your feedback :-)

**Comment by janegermaier** [comment]
Today we public new version, where u dont need selenium and other stuff. #84

**Comment by eldaduzman** [comment]
Thanks for the update @janegermaier, however it seems like the docs link is broken and there's nothing on the pypi page either.

**Comment by radekBednarik** [comment]
@eldaduzman minor update was published. On pypi, the links are working and readme is there as well. However, @janegermaier should update the https://tesena-smart-testing.github.io/WatchUI/keywords.html , last update is from October ;)
